services:
  # auth
  auth-service:
    container_name: auth-container
    build: ./auth
    env_file:
      - ./auth/config/auth.env
    depends_on:
      kafka:
        condition: service_started
    networks:
      - default

  postgres-auth:
    env_file:
      - ./auth/config/auth.env
    container_name: postgres-container
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: db
      POSTGRES_PORT: 5432
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
      - ./auth/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default


  #notify
  notify:
    env_file:
      - notify/.env
    container_name: notify-container
    build: ./notify
    networks:
      - default
    depends_on:
      kafka:
        condition: service_completed_successfully


  #search

  postgres-search:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
    volumes:
      - postgres_search_data:/var/lib/postgresql/data

    restart: on-failure

  redis:
    image: redis:7
    container_name: redis_container
    environment:
      REDIS_PORT: 6060
    volumes:
      - redis_data:/data

  search:
    build: ./search
    environment:
      - POSTGRES_HOST=postgres-search
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6060
      - KAFKA_BROKER=kafka:8080
      - KAFKA_REQUESTS_TOPIC=ads_request
      - KAFKA_NOTIFY_RESPONSES_TOPIC=ads_response
      - NOTIFY_SERVICE_NAME=search


    depends_on:
      - postgres-search
      - redis
      - kafka


  #gateway service

  gateway-service:
    build:
      context: ./gateway_service
    env_file:
      - gateway_service/.env
    environment:
      - REST_PORT=7070
      - KAFKA_HOST=kafka
      - KAFKA_PORT=8080
      - PROMETHEUS_PORT=9090
    depends_on:
      kafka:
        condition: service_started
    networks:
      - default

  kafka:
    image: 'bitnami/kafka:latest'
    networks:
      - default
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:8080,CONTROLLER://:8081
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:8081
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-container
    expose:
      - 9090
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    depends_on:
      gateway-service:
        condition: service_started
    networks:
      - default

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus




  nginx:
    image: nginx
    container_name: nginx-container
    ports:
      - "80:80"
    volumes:
      - ./gateway_service/proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      gateway-service:
        condition: service_started
    networks:
      - default

networks:
  default:


volumes:
  postgres_search_data:
  redis_data:
  postgres_auth_data: