services:
  # auth
  auth-service:
    container_name: auth-container
    build: ./auth
    env_file:
      - ./auth/config/auth.env
    depends_on:
      kafka1:
        condition: service_started
    networks:
      - default

  postgres-auth:
    env_file:
      - ./auth/config/auth.env
    container_name: postgres-container
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: db
      POSTGRES_PORT: 5432
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
      - ./auth/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default


  #notify
  notify:
    env_file:
      - notify/.env
    container_name: notify-container
    build: ./notify
    networks:
      - default
    depends_on:
      kafka1:
        condition: service_completed_successfully


  #search

  postgres-search:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
    volumes:
      - postgres_search_data:/var/lib/postgresql/data

    restart: on-failure

  redis:
    image: redis:7
    container_name: redis_container
    environment:
      REDIS_PORT: 6060
    volumes:
      - redis_data:/data

  search:
    build: ./search
    environment:
      - POSTGRES_HOST=postgres-search
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6060
      - KAFKA_BROKER=kafka1:9092
      - KAFKA_REQUESTS_TOPIC=ads_request
      - KAFKA_NOTIFY_RESPONSES_TOPIC=ads_response
      - NOTIFY_SERVICE_NAME=search


    depends_on:
      - postgres-search
      - redis
      - kafka1


  #gateway service

  gateway-service:
    build:
      context: ./gateway_service
    env_file:
      - gateway_service/.env
    environment:
      - REST_PORT=7070
      - KAFKA_HOST=kafka1
      - KAFKA_PORT=19092
      - PROMETHEUS_PORT=9090
    depends_on:
      kafka1:
        condition: service_started
    networks:
      - default

  kafka-uii:
    container_name: kafka-uii
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8082:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
    networks:
      - default

  zoo1:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zoo1
    container_name: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo1:2888:3888
    networks:
      - default

  kafka1:
    image: confluentinc/cp-kafka:7.3.2
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9999:9999"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    depends_on:
      - zoo1
    networks:
      - default



  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-container
    expose:
      - 9090
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    depends_on:
      gateway-service:
        condition: service_started
    networks:
      - default

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus




  nginx:
    image: nginx
    container_name: nginx-container
    ports:
      - "80:80"
    volumes:
      - ./gateway_service/proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      gateway-service:
        condition: service_started
    networks:
      - default

networks:
  default:


volumes:
  postgres_search_data:
  redis_data:
  postgres_auth_data: