lowercaseOutputName: true
rules:
  - pattern: "kafka.server<type=(.+), name=(.+)><>Value"
    name: "kafka_server_$1_$2"
    labels:
      instance: "kafka-broker"
  - pattern: "kafka.network<type=(.+), name=(.+)><>Value"
    name: "kafka_network_$1_$2"
    labels:
      instance: "kafka_broker"
  - pattern: "kafka.log<type=(.+), name=(.+)<>Value"
    name: "kafka_log_$1_$2"
    labels:
      instance: "kafka-broker"
