services:
  gateway-service:
    build:
      context: .
    env_file:
      - .env
    environment:
      - REST_PORT=${REST_PORT}
      - KAFKA_PORT=${KAFKA_PORT}
      - PROMETHEUS_PORT=${PROMETHEUS_PORT}
    ports:
      - "${REST_PORT}:${REST_PORT}"
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
    depends_on:
      kafka:
        condition: service_started
    networks:
      - default

  kafka:
    image: apache/kafka:2.7.0
    container_name: kafka-container
    env_file: .env
    environment:
      - KAFKA_PORT = ${KAFKA_PORT}
    ports:
      - "${KAFKA_PORT}:${KAFKA_PORT}"
    networks:
      - default

  prometheus:
    image: quay.io/prometheus/prometheus:latest
    env_file:
      - .env
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - default


  nginx:
    image: nginx
    container_name: nginx-container
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      gateway-service:
        condition: service_started
    networks:
      - default

networks:
  default: