global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "gateway"
    static_configs:
      - targets: ["gateway-service:7070"]
  - job_name: "kafka"
    static_configs:
      - targets: ["kafka:8080"]
  - job_name: "zookeeper"
    static_configs:
      - targets: ["zookeeper:2181"]